version: 7.0.0.{build}
image: Visual Studio 2017
shallow_clone: true
skip_branch_with_pr: true
skip_tags: true
configuration:
  - Test
  - Release

only_commits:
  files:
  - appveyor.yml
  - Source\*
  - Source\nuspecs\*

nuget:
  disable_publish_on_pr: true

init:
  - ps: $env:fullBuildVersion = $env:BuildVersion + $env:APPVEYOR_BUILD_NUMBER
  - ps: $env:fullBuildSemanticVersion = $env:BuildSemanticVersion + $env:APPVEYOR_BUILD_NUMBER
  - ps: Write-Host "Build Version:" $env:fullBuildVersion
  - ps: Write-Host "Build Semantic Version:" $env:fullBuildSemanticVersion
  - ps: Write-Host "Commit:" $env:APPVEYOR_REPO_COMMIT_MESSAGE 
  - ps: Write-Host "Commit extended:" $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED

assembly_info:
  patch: true
  file: 'Source\**\AssemblyInfo.cs'
  assembly_version: $(fullBuildVersion)
  assembly_file_version: $(fullBuildVersion)
  assembly_informational_version: $(fullBuildSemanticVersion)

environment:
  matrix:
  - solution_name: .\Source\PrismLibrary_Core.sln
  - solution_name: .\Source\PrismLibrary_Win10.sln
  - solution_name: .\Source\PrismLibrary_Wpf.sln
  - solution_name: .\Source\PrismLibrary_XF.sln
  - solution_name: .\Source\PrismLibrary.sln

before_build:
  - nuget restore %solution_name%

#build:
#  parallel: true
#  project: PrismLibrary.sln
#  verbosity: minimal

build_script:
  - msbuild %solution_name% 

test_script:
  - ps: .\test.ps1 -configuration $Configuration -solutionPath %solution_name%
  #- dotnet test Source\Prism.Tests\Prism.Tests.csproj -c Test
  #- vstest.console /logger:Appveyor Source\Wpf\\Prism.Wpf.Tests\bin\Release\Prism.Wpf.Tests.dll
  #- vstest.console /logger:Appveyor Source\Wpf\Prism.Autofac.Wpf.Tests\bin\Release\Prism.Autofac.Wpf.Tests.dll
  #- vstest.console /logger:Appveyor Source\Wpf\Prism.DryIoc.Wpf.Tests\bin\Release\Prism.DryIoc.Wpf.Tests.dll
  #- vstest.console /logger:Appveyor Source\Wpf\Prism.Mef.Wpf.Tests\bin\Release\Prism.Mef.Wpf.Tests.dll
  #- vstest.console /logger:Appveyor Source\Wpf\Prism.StructureMap.Wpf.Tests\bin\Release\Prism.StructureMap.Wpf.Tests.dll
  #- vstest.console /logger:Appveyor Source\Wpf\Prism.Unity.Wpf.Tests\bin\Release\Prism.Unity.Wpf.Tests.dll
  #- dotnet test Source\Xamarin\Prism.Autofac.Forms.Tests\Prism.Autofac.Forms.Tests.csproj -c Test
  #- dotnet test Source\Xamarin\Prism.DryIoc.Forms.Tests\Prism.DryIoc.Forms.Tests.csproj -c Test
  #- dotnet test Source\Xamarin\Prism.Forms.Tests\Prism.Forms.Tests.csproj -c Test
  #- dotnet test Source\Xamarin\Prism.Unity.Forms.Tests\Prism.Unity.Forms.Tests.csproj -c Test
  # UWP tests are not currently not supported by appveyor: https://github.com/appveyor/ci/issues/393

after_test:
  -ps: .\Source\nuspecs\nuget.ps1 -configuration %configuration% -solutionPath %solution_name%
  #- dotnet pack %solution_name%
  #on:
  #  Configuration: Release
  #  solution_name: 
  #- dotnet pack Source\Prism\PrismLibrary_XF.sln -c Release
  #- dotnet pack src\Prism.Forms\ -c Release
  #- dotnet pack src\Prism.Autofac.Forms\ -c Release
  #- dotnet pack src\Prism.DryIoc.Forms\ -c Release
  #- dotnet pack src\Prism.Ninject.Forms\ -c Release
  #- dotnet pack src\Prism.Unity.Forms\ -c Release
  #- powershell -f .\nuget.ps1

artifacts:
  - path: 'Source\Build\*.nupkg'
  - path: 'Source\nuspecs\Packages\*.nupkg'

deploy:
- provider: NuGet
  server: https://www.myget.org/F/prism-pre/api/v2/package
  api_key:
    secure: ZR2WeSlQqSkfL6YpxWzIqhdeKSdxxPqp9yvN7l+SyIX+yIHNcKNqCENWcE8A6GsQ
  skip_symbols: false
  on:
    branch: master
    Configuration: Release