version: 7.0.0.{build}
image: Visual Studio 2017
shallow_clone: true
skip_branch_with_pr: true
skip_tags: true
configuration:
  - Test
  - Debug
  - Release

only_commits:
  files:
  - appveyor.yml
  - Source\*
  - Source\nuspecs\*
  - Sandbox\*

skip_commits:
  files:
    - '**/*.md'

nuget:
  disable_publish_on_pr: true

init:
  - ps: $env:fullBuildVersion = $env:BuildVersion + $env:APPVEYOR_BUILD_NUMBER
  - ps: $env:fullBuildSemanticVersion = $env:BuildSemanticVersion + $env:APPVEYOR_BUILD_NUMBER
  - ps: Write-Host "Version $version"
  - ps: Write-Host "Build Version:" $env:fullBuildVersion
  - ps: Write-Host "Build Semantic Version:" $env:fullBuildSemanticVersion
  - ps: Write-Host "Commit:" $env:APPVEYOR_REPO_COMMIT_MESSAGE 
  - ps: Write-Host "Commit extended:" $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED

assembly_info:
  patch: true
  file: 'Source\**\AssemblyInfo.cs'
  assembly_version: "1.0.0.0"
  assembly_informational_version: "7.0.0-build{build}"

environment:
  matrix:
  - solution_name: .\Source\PrismLibrary_Core.sln
  - solution_name: .\Source\PrismLibrary_Win10.sln
  - solution_name: .\Sandbox\Windows10\HelloWorld\HelloWorld.sln
  - solution_name: .\Source\PrismLibrary_Wpf.sln
  - solution_name: .\Source\PrismLibrary_XF.sln
  - solution_name: .\Sandbox\Xamarin\HelloWorld\HelloWorld.sln
  - solution_name: .\Source\PrismLibrary.sln

matrix:
  exclude:
    # PrismLibrary.sln should only be built in release for the NuGet pack
    - solution_name: .\Source\PrismLibrary.sln
      configuration: Test
    - solution_name: .\Source\PrismLibrary.sln
      configuration: Debug
    # PrismLibrary_Core, PrismLibrary_Win10, & PrismLibrary_Wpf only need to build in Release
    - solution_name: .\Source\PrismLibrary_Core.sln
      configuration: Test
    - solution_name: .\Source\PrismLibrary_Core.sln
      configuration: Debug
    - solution_name: .\Source\PrismLibrary_Win10.sln
      configuration: Test
    - solution_name: .\Source\PrismLibrary_Win10.sln
      configuration: Debug
    - solution_name: .\Source\PrismLibrary_Wpf.sln
      configuration: Test
    - solution_name: .\Source\PrismLibrary_Wpf.sln
      configuration: Debug
    # PrismLibrary_XF.sln can only be tested with the Test configuration
    - solution_name: .\Source\PrismLibrary_XF.sln
      configuration: Debug
    # The Sandbox solutions should only be built in debug for validation
    - solution_name: .\Sandbox\Windows10\HelloWorld\HelloWorld.sln
      configuration: Test
    - solution_name: .\Sandbox\Windows10\HelloWorld\HelloWorld.sln
      configuration: Release
    - solution_name: .\Sandbox\Xamarin\HelloWorld\HelloWorld.sln
      configuration: Test
    - solution_name: .\Sandbox\Xamarin\HelloWorld\HelloWorld.sln
      configuration: Release

before_build:
  - nuget restore %solution_name%

build_script:
  - msbuild %solution_name% 

test_script:
  # UWP tests are not currently not supported by appveyor: https://github.com/appveyor/ci/issues/393
  - ps: .\tools\test.ps1 -configuration $env:Configuration -solutionPath $env:solution_name

after_test:
  #- dotnet pack %solution_name%
  -ps: .\Source\nuspecs\nuget.ps1 -configuration $env:Configuration -solutionPath $env:solution_name

artifacts:
  - path: 'Build\*.nupkg'
  - path: 'Source\Build\*.nupkg'
  - path: 'Source\nuspecs\Packages\*.nupkg'

deploy:
- provider: NuGet
  server: https://www.myget.org/F/prism-pre/api/v2/package
  api_key:
    secure: ZR2WeSlQqSkfL6YpxWzIqhdeKSdxxPqp9yvN7l+SyIX+yIHNcKNqCENWcE8A6GsQ
  skip_symbols: false
  on:
    branch: master
    Configuration: Release