name: dotnet_format

on:
  pull_request:
    branches:
      - master
    paths:
      - 'e2e/**'
      - 'src/**'
      - 'tests/**'

jobs:
  dotnet_format:
    runs-on: windows-latest
    steps:
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run dotnet format
        id: format
        uses: jfversluis/dotnet-format@v1.0.9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          only-changed-files: true
          workspace: "PrismLibrary.sln"
